---
- name: Raspberry Pi Speicherstatus abfragen
  hosts: all
  gather_facts: no
  tasks:
    - name: Überprüfe freien Speicher
      shell: df -h | grep '/$' | awk '{print $4}'
      register: free_space

    - name: Zeige freien Speicher
      debug:
        msg: "Freier Speicher: {{ free_space.stdout }}"